apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop.fullname" . }}-api
  labels:
    {{- include "shop.labels" . | nindent 4 }}
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000 # This must match the port your NestJS app listens on
      protocol: TCP
      name: http
  selector:
    {{- include "shop.selectorLabels" . | nindent 4 }}
    component: api