apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env.mysqlHost }}
  labels:
    {{- include "shop.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3306
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: {{ .Values.env.mysqlHost }}
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.images.mysql }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "shop.fullname" . }}-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE        # <--- ADD THIS BLOCK
          value: "shopping_db"
        ports:
        - containerPort: 3306