# ui/Dockerfile
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
# We no longer COPY the nginx.conf here; 
# Kubernetes will provide it via the volume mount!
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80